### ISSUE TITLE
[Bug] Hermitron cases destroyed by non-player lose contents

### ISSUE THREAD

**Issue by Carbon-Key** [Zairus/Hermitron#2]
Had some TNT go off next to some Hermitron cases and the dropped cases lost the items inside. If this is intended then that's fine, thought I'd post this just in case it wasn't. Next time I'll just not let TNT blow up my cases. :P

**Comment by WinterGrave** [comment]
This is a known issue and working about it, will close this issue and hopefully I can sort it out for next update. Thanks!
