### ISSUE TITLE
[suggestion] Command to spawn the Hermitrons

### ISSUE THREAD

**Issue by andre-paulo98** [Zairus/Hermitron#4]
I was wondering if its possible to disable the world gen of the Hermitrons (already found out you can on the configs file), and if its possible to randomly spawn them from time to time with a command or automatic on the mod.
Why?
On a public server new players don't have much a chance to play this. All the players that joined first might already explored the world just to find them.
So i think it would be more fun to randomly them spawn, and maybe say where they spawn (approximated coords), so players have to go there to grab them.

**Comment by WinterGrave** [comment]
The problem with this is that they would spawn on built terrain and may destory builds

**Comment by andre-paulo98** [comment]
Hmm lets say i run /hermitron randomspawn x1 z1 x2 z2
You could generate 2 random numbers between x and z and check if there is "space" for them to spawn.
1. Check where on y is the first block (on surface)
2. Get the coords of that block and increment 2 on y
3. Expand 1 on both negatives and positives on x, y, z.
4. If its all Air or Grass (those bushes) then generate a Hermitron. If not repeat.

**Comment by andre-paulo98** [comment]
Any updates?

**Comment by WinterGrave** [comment]
Implemented command hermitron_generate <x> <y> <z> in version 0.2.13, if no coords are specified, it generates at player position on the next available surface.
